name: FastAPI Deploy via ECR and SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: aws자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.FASTAPI_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ secrets.FASTAPI_IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./fastapi
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2 via SSM
        run: |
          IMAGE_URL="${{ steps.login-ecr.outputs.registry }}/${{ secrets.FASTAPI_ECR_REPOSITORY }}:${{ secrets.FASTAPI_IMAGE_TAG }}"
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              \"aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}\",
              \"sudo docker pull ${IMAGE_URL}\",
              \"sudo docker stop fastapi-container || true\",
              \"sudo docker rm fastapi-container || true\",
              \"sudo docker run -d --name fastapi-container -p 8000:8000 ${IMAGE_URL}\"
            ]" \
            --comment "Deploy FastAPI container on EC2 using SSM" \
            --timeout-seconds 600 \
            --region ${{ secrets.AWS_REGION }}